/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonajesRouteImport } from './routes/personajes'
import { Route as LugaresRouteImport } from './routes/lugares'
import { Route as FamiliaRouteImport } from './routes/familia'
import { Route as EspeciaRouteImport } from './routes/especia'
import { Route as CodiceRouteImport } from './routes/codice'
import { Route as ChakobsaRouteImport } from './routes/chakobsa'
import { Route as CasasRouteImport } from './routes/casas'
import { Route as IndexRouteImport } from './routes/index'

const PersonajesRoute = PersonajesRouteImport.update({
  id: '/personajes',
  path: '/personajes',
  getParentRoute: () => rootRouteImport,
} as any)
const LugaresRoute = LugaresRouteImport.update({
  id: '/lugares',
  path: '/lugares',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaRoute = FamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const EspeciaRoute = EspeciaRouteImport.update({
  id: '/especia',
  path: '/especia',
  getParentRoute: () => rootRouteImport,
} as any)
const CodiceRoute = CodiceRouteImport.update({
  id: '/codice',
  path: '/codice',
  getParentRoute: () => rootRouteImport,
} as any)
const ChakobsaRoute = ChakobsaRouteImport.update({
  id: '/chakobsa',
  path: '/chakobsa',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasRoute = CasasRouteImport.update({
  id: '/casas',
  path: '/casas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casas': typeof CasasRoute
  '/chakobsa': typeof ChakobsaRoute
  '/codice': typeof CodiceRoute
  '/especia': typeof EspeciaRoute
  '/familia': typeof FamiliaRoute
  '/lugares': typeof LugaresRoute
  '/personajes': typeof PersonajesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casas': typeof CasasRoute
  '/chakobsa': typeof ChakobsaRoute
  '/codice': typeof CodiceRoute
  '/especia': typeof EspeciaRoute
  '/familia': typeof FamiliaRoute
  '/lugares': typeof LugaresRoute
  '/personajes': typeof PersonajesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/casas': typeof CasasRoute
  '/chakobsa': typeof ChakobsaRoute
  '/codice': typeof CodiceRoute
  '/especia': typeof EspeciaRoute
  '/familia': typeof FamiliaRoute
  '/lugares': typeof LugaresRoute
  '/personajes': typeof PersonajesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casas'
    | '/chakobsa'
    | '/codice'
    | '/especia'
    | '/familia'
    | '/lugares'
    | '/personajes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casas'
    | '/chakobsa'
    | '/codice'
    | '/especia'
    | '/familia'
    | '/lugares'
    | '/personajes'
  id:
    | '__root__'
    | '/'
    | '/casas'
    | '/chakobsa'
    | '/codice'
    | '/especia'
    | '/familia'
    | '/lugares'
    | '/personajes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasasRoute: typeof CasasRoute
  ChakobsaRoute: typeof ChakobsaRoute
  CodiceRoute: typeof CodiceRoute
  EspeciaRoute: typeof EspeciaRoute
  FamiliaRoute: typeof FamiliaRoute
  LugaresRoute: typeof LugaresRoute
  PersonajesRoute: typeof PersonajesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personajes': {
      id: '/personajes'
      path: '/personajes'
      fullPath: '/personajes'
      preLoaderRoute: typeof PersonajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lugares': {
      id: '/lugares'
      path: '/lugares'
      fullPath: '/lugares'
      preLoaderRoute: typeof LugaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia': {
      id: '/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof FamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especia': {
      id: '/especia'
      path: '/especia'
      fullPath: '/especia'
      preLoaderRoute: typeof EspeciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codice': {
      id: '/codice'
      path: '/codice'
      fullPath: '/codice'
      preLoaderRoute: typeof CodiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chakobsa': {
      id: '/chakobsa'
      path: '/chakobsa'
      fullPath: '/chakobsa'
      preLoaderRoute: typeof ChakobsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casas': {
      id: '/casas'
      path: '/casas'
      fullPath: '/casas'
      preLoaderRoute: typeof CasasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasasRoute: CasasRoute,
  ChakobsaRoute: ChakobsaRoute,
  CodiceRoute: CodiceRoute,
  EspeciaRoute: EspeciaRoute,
  FamiliaRoute: FamiliaRoute,
  LugaresRoute: LugaresRoute,
  PersonajesRoute: PersonajesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
